version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd src/WDP301_Project/client # Di chuyển đến thư mục chứa package.json
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
