export const apiGetInforByGoogleLogin = "https://www.googleapis.com/oauth2/v3/userinfo"
export const apiLogin = "account/login"
export const apiLoginByGoogle = "account/loginByGoogle"
export const apiRegister = "account/register"
export const apiRegisterByGoogle = "account/registerByGoogle"
export const apiGetDetailProfile = "user/getDetailProfile"
export const apiChangeProfile = "user/changeProfile"